name: Remote Ubuntu
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update and Download Essential Software
        run: | 
          sudo apt-get update -y && sudo apt-get upgrade -y
          sudo apt-get install -y  ubuntu-gnome-desktop xorg xterm gdm3 menu synaptic p7zip-full
      - name: Check localtonet TCP
        run: | 
          curl -L https://localtonet.com/download/localtonet-linux-x64.zip -o localtonet-linux-x64.zip &> nul
          7z x localtonet-linux-x64.zip
          sudo ./localtonet authtoken ${{ secrets.LOCALTONET_AUTH_TOKEN_INFO }}
      - name: Running RDP
        run: | 
          sudo dpkg-reconfigure gdm3
          sudo service gdm3 start
      - name: Running time loop
        run: while :; do sleep 2073600; done
