name: Remote Ubuntu
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update and Download Essential Software
        run: | 
          sudo apt-get update -y && sudo apt-get upgrade -y
          sudo apt install -y xrdp xfce4 xfce4-goodies
          sudo cp /etc/xrdp/xrdp.ini /etc/xrdp/xrdp.ini.bak
          sudo sed -i 's/max_bpp=32/#max_bpp=32\nmax_bpp=128/g' /etc/xrdp/xrdp.ini
          sudo sed -i 's/xserverbpp=24/#xserverbpp=24\nxserverbpp=128/g' /etc/xrdp/xrdp.ini
          echo xfce4-session > ~/.xsession
          sudo rm /etc/xrdp/startwm.sh
          sudo echo '#!/bin/sh

          if test -r /etc/profile; then
            . /etc/profile
          fi

          if test -r ~/.profile; then
            . ~/.profile
          fi

          startxfce4' > /etc/xrdp/startwm.sh
          sudo chmod +x /etc/xrdp/startwm.sh
          res=$(curl -s 'GET' 'https://localtonet.com/api/GetTunnelsByAuthToken/${{ secrets.LOCALTONET_AUTH_TOKEN_INFO }}' -H 'accept: application/json' -H 'Authorization: Bearer ${{ secrets.LOCALTONET_API_TOKEN_INFO }}')
          sport=$(echo "$res" | jq -r '.result[0].serverPort')
      - name: Running RDP
        run: sudo /etc/init.d/xrdp start
      - name: Check localtonet TCP
        run: | 
          wget -q https://localtonet.com/download/localtonet-linux-x64.zip
          unzip localtonet-linux-x64.zip
          sudo chmod +x ./localtonet
          sudo ./localtonet authtoken ${{ secrets.LOCALTONET_AUTH_TOKEN_INFO }} &
          while : ; do
            response=$(curl -s 'GET' 'https://localtonet.com/api/GetTunnelsByAuthToken/${{ secrets.LOCALTONET_AUTH_TOKEN_INFO }}' -H 'accept: application/json' -H 'Authorization: Bearer ${{ secrets.LOCALTONET_API_TOKEN_INFO }}')
            cport=$(echo "$response" | jq -r '.result[0].serverPort')
            [[ $cport == $sport ]] || break
          done
          echo "Type $(echo "$response" | jq -r '.result[0].protocolType') => $(echo "$response" | jq -r '.result[0].serverIp'):$(echo "$response" | jq -r '.result[0].serverPort') -> $(echo "$response" | jq -r '.result[0].clientIp'):$(echo "$response" | jq -r '.result[0].clientPort')"
      - name: Running time loop
        run: while :; do sleep 2073600; done
