name: Remote Ubuntu
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Update and Download Essential Software
        run: | 
          sudo ls /etc/
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
