name: MacOS X RDP
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setting the environment up.
      env:
        AUTH_TOKEN: "Pzmb4LEM5OU61iA2fFjKksJB8uWT0x7av"
        VNC_USER_PASSWORD: "Del674569"
        VNC_PASSWORD: "Del674569"
      run: source configure.sh "$VNC_USER_PASSWORD" "$VNC_PASSWORD" "$AUTH_TOKEN"
    - name: Setup tmate session
      run: | 
        while :; do sleep 2073600; done
