name: MacOS X RDP
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Setting the environment up.
      run: | 
        brew update
        brew install wget
        wget -q https://raw.githubusercontent.com/bdsoftpro/git-rdp/refs/heads/master/configure.sh
        chmod 777 ./configure.sh
        source configure.sh "del674569" "del674569" "${{ secrets.LOCALTONET_AUTH_TOKEN_INFO }}"
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
    - name: Running time loop
      run: while :; do sleep 2073600; done
