name: Remote Desktop
env:
  Name: "administrator"
  Pwd:	"Del674569"
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Check localtonet TCP
        run: | 
          $Res = Invoke-WebRequest -Uri "https://localtonet.com/api/GetTunnelsByAuthToken/${{ secrets.LOCALTONET_AUTH_TOKEN }}" -Method:Get -Headers @{"Authorization"="Bearer ${{ secrets.LOCALTONET_API_TOKEN }}"; "Accept"="application/json"} -UseBasicParsing
          $Cnt = ConvertFrom-JSON -InputObjec $Res.Content
      - name: Downloading and Installing Essential.
        run: | 
          Invoke-WebRequest https://localtonet.com/download/localtonet-win-64.zip -OutFile localtonet.zip
          Invoke-WebRequest https://raw.githubusercontent.com/bdsoftpro/git-rdp/master/start.bat -OutFile start.bat
          Invoke-WebRequest https://raw.githubusercontent.com/bdsoftpro/git-rdp/master/wallpaper.png -OutFile wallpaper.png
          Invoke-WebRequest https://raw.githubusercontent.com/bdsoftpro/git-rdp/master/wallpaper.bat -OutFile wallpaper.bat
          Invoke-WebRequest https://vscode.download.prss.microsoft.com/dbazure/download/stable/d78a74bcdfad14d5d3b1b782f87255d802b57511/VSCodeSetup-x64-1.94.0.exe -OutFile VSCodeSetup.exe
          Invoke-WebRequest https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.7/npp.8.7.Installer.x64.exe -OutFile npp.8.6.7.Installer.x64.exe
      - name: Extracting Localtonet Files.
        run: Expand-Archive localtonet.zip
      - name: Connecting to your Localtonet account.
        run: Start-Process -FilePath ".\localtonet\localtonet.exe" -ArgumentList "authtoken ${{ secrets.LOCALTONET_AUTH_TOKEN }}"
      - name: Activating RDP access.
        run: | 
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
          copy wallpaper.png D:\a\wallpaper.png
          copy wallpaper.bat D:\a\wallpaper.bat
      - name: Installing Other Tools
        run: | 
          Start-Process -FilePath .\VSCodeSetup.exe -ArgumentList '/verysilent /mergetasks=!runcode' -Wait -Passthru > null
          Start-Process -FilePath .\npp.8.6.7.Installer.x64.exe -Args "/S" -Verb RunAs -Wait
      - name: Connecting to your RDP.
        run: | 
          Do {
            $Response = Invoke-WebRequest -Uri "https://localtonet.com/api/GetTunnelsByAuthToken/${{ secrets.LOCALTONET_AUTH_TOKEN }}" -Method:Get -Headers @{"Authorization"="Bearer ${{ secrets.LOCALTONET_API_TOKEN }}"; "Accept"="application/json"} -UseBasicParsing
            $Content = ConvertFrom-JSON -InputObjec $Response.Content
          }While ($Content.result.serverPort -eq $Cnt.result.serverPort)
          $Link = "Type: "+$Content.result.protocolType+" => "+$Content.result.serverIp+":"+$Content.result.serverPort+" -> "+$Content.result.clientIp+":"+$Content.result.clientPort
          cmd /c start.bat ${{ env.Name }} ${{ env.Pwd }} $Link
      - name: Time Counter
        run: Do {Start-Sleep -Seconds 10;} While (2 -eq 2)
